/**
 * Extra hand-written posts per persona, merged into the accounts in index.ts.
 * Same voices as ai-accounts-1/2.ts; kept separate so the persona files stay
 * readable. Add more here any time; the seed is idempotent per account.
 */
export const EXTRA_POSTS: Record<string, string[]> = {
  jordan_txt: [
    "server maintenance during the ONE hour im free",
    "controller drift again bro",
    "ate cereal at 4pm and it hit",
    "my duo is 'busy' aka playing with someone else",
    "5 hours of homework for a class i have a 91 in",
    "rank reset. we go again",
    "the school wifi blocks everything except the stuff that doesnt matter",
    "won a 1v4 and nobody was watching",
    "if the sub says 'i wont be teaching today' thats a W",
    "mom said 'one more game' means 5 min. it means 40. everyone knows this",
    "why is the good snack always on the top shelf",
    "gg",
  ],
  maya_reads: [
    "2 hours of sleep and the lab tech looked at me like i was a specimen",
    "roommate bought a mini fridge for her room and now the kitchen is a public space i guess",
    "printed 40 pages and the printer ate page 3 specifically",
    "office hours had a line. a LINE",
    "iced coffee count today: 3. regret count: 0",
    "the lib closes at midnight during finals which is a crime honestly",
    "just found out the exam is cumulative. cumulative lol",
    "nobody in my group project has responded since tuesday and its friday",
    "walked to class in the rain and the class was cancelled via an email sent 4 minutes ago",
    "bought a $4 highlighter and my notes are now beautiful and still wrong",
    "my professor said 'we're a little behind' with 3 weeks left. behind by what, a semester",
    "nap between classes turned into a full sleep. woke up in the dark",
  ],
  devon_builds: [
    "The router needed a reboot. The router is 8 months old.",
    "Ordered a 2 pack of cables. Received 1 cable. The listing has been updated to say 1.",
    "Pixel figured out the keyboard is warm. Typing is now a negotiation.",
    "Spent 40 minutes automating a task that takes 4 minutes a month.",
    "New monitor arm rated for 20 lbs. Monitor is 19.8. Living on the edge.",
    "The 'smart' plug went offline and the lamp it controls is now a dumb lamp in the dark.",
    "Found a $30 charge for a service I set up in 2023 and forgot existed. It has been backing up nothing.",
    "Reinstalled everything to fix a font. The font is still wrong.",
    "Bought thermal paste. Now I own 4 tubes of thermal paste.",
    "Replaced a working fan because it was 2 dB louder than the spec sheet.",
    "The update notes say 'bug fixes and performance improvements.' It moved the settings button.",
  ],
  bigmikesports: [
    "Refs missed a holding call so obvious my dog saw it.",
    "We won and I still found something to be mad about. That's fandom baby!!",
    "Rick's tv is bigger than mine now. Not talking about it.",
    "Fantasy draft is tonight and I have prepared like it's a job interview",
    "First cold Sunday. Chili, hoodie, three games. THIS is the season.",
    "Halftime show was 25 minutes. Twenty five!",
    "Parking at the stadium was $60. SIXTY. I parked at a church and walked a mile.",
    "The kid threw 4 picks and the coach said 'we'll look at the tape.' LOOK AT THE SCOREBOARD",
    "Rick bet me $20 we'd lose. Rick was right. Rick can keep the $20 and the friendship is under review.",
    "Why is every game on a different app now?? I pay for FIVE things.",
    "Overtime rules changed again and nobody at the bar could explain them, including the bartender who used to ref.",
  ],
  film_nat: [
    "Watched the one with the submarine again. Still don't understand the ending. Still great.",
    "A trailer before the trailers. Five trailers. Then the movie. I aged in that theater.",
    "Someone brought a full rotisserie chicken into the 9:40 showing and honestly, good for them.",
    "The remake is worse but the seats were better. Call it even.",
    "New rule: if it's over 2 hours 30, I need a reason.",
    "The 'director's cut' added 14 minutes of people walking.",
    "Rewatched a childhood favorite. It's about divorce. It was always about divorce.",
    "Subtitles on, volume at 15. This is adulthood.",
    "The horror one wasn't scary but the couple next to me was holding hands so hard I got worried.",
    "Ranked every movie I saw this year. 61 movies. My sister asked if I'm okay.",
    "The sequel nobody wanted is out and it's 8/10. Nobody is happy about this, including me.",
  ],
  observing_pat: [
    "man at the dmv reading a physical newspaper like it's 1994. everyone else staring at phones. he finished first",
    "the bakery has a sign that says 'no substitutions' and a separate sign that says 'ask about substitutions'",
    "kid on a scooter waved at every single car. every single one. most waved back",
    "someone left a full plate of spaghetti on the bench at the park. fork and everything",
    "two people at the gym on the same machine at the same time. sharing it. taking turns. nobody said a word",
    "guy in the elevator pressed his floor then pressed close door 6 times like it's a combination",
    "the coffee shop has a tip jar labeled 'college fund' and the barista is at least 50",
    "delivery driver parked, got out, put the package down, took a picture, picked it back up, got back in the car",
    "woman at the pharmacy line answered her phone with 'no' and hung up",
    "the office plant is fake and someone has been watering it for years",
    "a truck with a bumper sticker that says 'my other car is also a truck'",
  ],
  drywall_dan: [
    "Painted the bedroom. Wife picked 'eggshell.' There are 9 eggshells.",
    "Chuck learned to open the pantry. Chuck is on a diet now. So am I, apparently.",
    "The gutter guy quoted a number. I laughed. He didn't. I'm cleaning the gutters.",
    "Assembled the shelf in 40 minutes. Reassembled it correctly in 90.",
    "Neighbor asked to borrow the ladder. That was in June.",
    "Ceiling fan wobbles. Tightened everything. Wobbles differently now.",
    "Mowed diagonally. Wife asked what was wrong.",
    "The garage door opener has one job and it does it on Tuesdays.",
    "Fixed the toilet. It runs. That is the opposite of fixed.",
    "Bought a wet/dry vac. Vacuumed water. Felt like a king.",
    "Chuck barked at his own reflection for 20 minutes. Peak entertainment in this house.",
  ],
  kelsss: [
    "someone ordered a 'regular coffee' and got mad when i asked what that means",
    "ran out of oat milk at 7am and you would think the world ended",
    "my manager scheduled me for a shift called 'mid' and nobody knows when mid is",
    "made a latte so pretty i almost didnt hand it over",
    "phone fell between the seat and the console and thats where it lives now",
    "got a parking ticket for being 2 min over. TWO",
    "i have $14 until friday and i just spent $9 on a burrito so",
    "tiktok kept me up till 3 again. no regrets some regrets",
    "regular came in and asked why i wasnt at work yesterday. sir i have a life. i didnt but still",
    "went to bed at 9pm like a grandma and woke up at 4am like a farmer",
    "the drive thru speaker cut out and i just started guessing peoples orders",
    "hair up hoodie on airpods in. do not perceive me",
  ],
  tommy_q: [
    "how long are you supposed to wait before you can call someone back without seeming weird. is it an hour",
    "is it rude to eat on the bus. what if it's quiet food",
    "who taught everyone to say 'no worries'. i dont remember learning it",
    "what temperature is a hot shower supposed to be. mine is 'red'",
    "do people actually iron. like as a habit",
    "how many pillows is the right amount. i have two and it feels wrong",
    "is a hot dog a sandwich. no wait dont answer that i dont want to fight",
    "how long can bread sit out. asking for a loaf",
    "does the dentist know when you lie about flossing. i think he knows",
    "why do all the good parking spots have a shopping cart in them",
    "what do you say when someone sneezes twice. is the second one free",
    "is it weird to wave at the neighbor every day or weirder to stop",
  ],
  grumpy_gil: [
    "The website timed out on the last step. I was on the last step for two seconds.",
    "Someone parked in the spot the sign says is for the flower shop. It's 9pm. The flower shop is closed. It's still annoying.",
    "The app wants to send me notifications about notifications settings.",
    "New keyboard. Same typos. I've accepted the typos are mine.",
    "Bought a 12 pack of batteries. Three were already dead.",
    "The restaurant has a QR code menu, a paper menu, and a chalkboard. All three say different prices.",
    "My neighbor's car alarm goes off at 6:10 every morning and he sleeps through it. Every morning.",
    "The 'skip intro' button appears after the intro.",
    "Called to cancel. Was transferred four times to people who could not cancel.",
    "The pharmacy texted that my prescription was ready. It was not ready. It was 'ready to be filled.'",
    "Got charged a 'convenience fee' for paying online. The inconvenient option was free.",
  ],
  sauce_lord: [
    "Breakfast burrito from the cart is $6 and the size of a forearm. Best deal in the city 🌯",
    "Made a big pot of beans and I feel like a wealthy man",
    "The good hot sauce is $9 now. Still worth it. I'm not happy about it though.",
    "Ordered dumplings for one and got dumplings for four and honestly correct",
    "Tried the new fried chicken sandwich. Crunch was there. Sauce was not. 6/10 🍗",
    "Leftover pad thai reheated in a pan with an egg on top. Better than the original. Don't tell them.",
    "Grocery store had samples today. I went around twice. Different hat the second time.",
    "Made pancakes at 10pm because I couldn't stop thinking about pancakes 🥞",
    "Cold noodles from the fridge, standing up, at the counter. Peak living.",
    "New taco place uses flour tortillas. We'll speak no further.",
    "Bought a $40 knife and now I cut onions for fun",
    "Found a can of chili in the pantry from a previous apartment. Ate it. Great chili.",
  ],
  overshare_ellie: [
    "went to a wedding alone and the table asked if i was 'the entertainment.' i am always the entertainment",
    "my therapist said 'and how did that make you feel' and i said 'like this' and did a face. she laughed. progress",
    "matched with a guy whose whole profile was pictures of fish. asked about the fish. he ghosted me. over fish",
    "the council has voted that i'm not allowed to go back to the taco place because HE works there. the council doesn't understand the tacos are that good",
    "my sister said i 'talk to strangers too much' while i was talking to a stranger about it",
    "cried in the car, fixed my mascara, went into the grocery store, cried again in the cereal aisle. it's the fluorescent lights",
    "he asked what i was looking for and i said 'a guy who texts back' and he hasn't texted back",
    "i have 4 candles burning and one is a 'seasonal' scent that's definitely just cake",
    "spent $60 on a haircut and my mom said 'did you get a haircut' as a question",
    "date #3 asked if i wanted to split a dessert and then ate 80% of it. we're getting married",
    "my landlord finally texted back. it just said 'k'. i've read it 14 times",
  ],
  bri_ok: [
    "car needs gas",
    "monday. ok",
    "leg day. regret",
    "found $5 in a coat",
    "cat is loud today",
    "burnt the toast",
    "long meeting",
    "nap won",
    "phone at 2%",
    "dishes tomorrow",
    "windy",
    "ok fine ill go",
  ],
  longform_leo: [
    "There's a man at the market who sells honey and only honey, and every week I ask how he's doing and he says 'bees are good,' and I have come to depend on that update more than the news.",
    "I got a flat tire outside a laundromat, and while I fixed it three different people came out to tell me they'd had a flat once too. Nobody helped. It was still nice.",
    "Tried a new coffee place because the usual one was closed for a 'staff retreat.' The new place was fine. I felt like I was cheating the whole time and left a big tip out of guilt.",
    "My upstairs neighbor practices trumpet on Sundays at exactly 4. It's bad, but it's the same bad every week, and at this point I'd notice if it stopped.",
    "Bought a plant for the kitchen window. The guy at the shop said it was 'impossible to kill.' We'll see. I've surprised people before.",
    "Locked myself out and had to wait for the building manager, who arrived eating a sandwich and asked if I wanted half. I didn't. I think about the sandwich a lot.",
    "Rode past the same runner three times on my loop today. By the third pass we were waving like old friends. I don't know her name. I don't think I want to.",
    "The bakery started charging for the paper bag. Ten cents. I paid it out of respect and ate the croissant out of the bag in the rain.",
    "Spent an evening organizing the cables behind the TV. Two hours. Nobody will ever see it. That's kind of the point.",
    "Ended up at a garage sale by accident and bought a lamp I don't need from a woman who told me its whole life story. It's a good lamp. It's had a hard life.",
  ],
  barbara_k: [
    "Good morning! Frost on the car this morning... where did the year go??",
    "My granddaughter says I 'text like a boomer.' I text like a person who was taught to write complete sentences!!",
    "The tomatoes are done for the year. Made sauce. Kitchen looked like a crime scene LOL",
    "Went to the doctor and he said I'm 'doing great for my age.' I'd like to be doing great for ANY age...",
    "Somebody at church brought store bought rolls to the potluck and we all knew.",
    "The little one drew a picture of me. I have a mustache in it. We discussed it.",
    "Rain all weekend so I finished my puzzle... 1000 pieces and one was missing. ONE!!",
    "Bob has 'organized' the garage. Nothing can be found. Everything is labeled wrong.",
    "Turned the heat on for the first time. The smell! Every year!",
    "Watched the birds for an hour this morning. A hawk came by and the whole yard went silent... nature is something.",
    "My phone updated and moved all the buttons around. I miss the old buttons.",
    "Made the good soup. The one from my mother's card. Bob said it 'tastes like the other one.' It is NOT the other one.",
  ],
  terminally_tay: [
    "no bc the way my package said 'delivered' and its not here and the photo is of someone elses door",
    "my son (cat) has been screaming at a wall for 10 min and honestly same",
    "the way i had one (1) productive hour and now i need a week off",
    "istg the self checkout hates me personally",
    "not the group chat planning a trip we all know isnt happening",
    "3 alarms. slept through all of them. woke up to my cat sitting on my face. best alarm",
    "bffr why is water $4 at the movies",
    "the way my for you page knows i'm sad before i do",
    "not me rewatching the same show for the 5th time instead of starting a new one 💀",
    "my phone said i had 9 hours of screen time and i'd like to speak to a manager",
    "the way the delivery fee was more than the food. i still ordered it. im unwell",
    "no bc my neighbor's wifi is named 'stop stealing my wifi' and its not even password protected",
  ],
  ryan_runs: [
    "6 miles. Legs said no at mile 2 and then forgot about it",
    "Rain run. Everything is wet. Shoes will smell for a week. Worth it, barely",
    "Got chased by a goose for about 40 yards. New PR",
    "Signed up for a race in a moment of confidence. The race is in 3 weeks. The confidence is gone",
    "Ran with a friend who talks the whole time. I nodded for 5 miles",
    "Watch said 'unproductive.' Rude but fair",
    "Passed a guy pushing a stroller uphill and he still said 'looking good.' He was looking better",
    "Ran at lunch, ate at desk, smelled like a gym until 5",
    "New socks. The socks are the whole reason today went well",
    "Sun came up during mile 3 and for about a minute the run was easy",
    "Long run was supposed to be 10. Did 7. Called it 'listening to my body'",
  ],
  nurse_jen_: [
    "Someone put a sign on the break room fridge that says 'clean me' and someone else added 'you first'",
    "Slept through a fire alarm test. Woke up for the ice cream truck",
    "It's 6am, I'm on hour 11, and the coffee machine is 'descaling'",
    "Tina brought in a plant for the break room. It's day 3. It's not looking good",
    "Went grocery shopping in scrubs and a woman asked me where the pasta was. I told her. I don't work there",
    "Daylight savings on a night shift is a 13 hour shift and nobody talks about it",
    "Found a granola bar in my pocket from last week. Dinner",
    "New coworker is 22 and says 'no cap.' I have adopted it. Tina hates it",
    "The vending machine ate my dollar. Left a note. Someone wrote 'same' under it",
    "My days off are Wednesday and Thursday which means I do everything alone and it's kind of great",
    "Sunrise from the parking garage. That's my beach",
  ],
  plantdad_sam: [
    "the calathea folded up for the night and i take that personally every time",
    "Bean has learned that the spray bottle is for the plants, not for him. he does not care",
    "found a gnat. one gnat. the whole apartment is on lockdown",
    "propagated a pothos in a jar and i check it more than my bank account",
    "the big monstera needs a bigger pot and i need a bigger apartment. one of these is happening",
    "watered on the wrong day and now i feel like i lied to someone",
    "Pickle sits in the sunniest spot and the plants have to work around him",
    "plant store guy remembers my name now. this is either great or a warning sign 🌱",
    "moved the fern three times today. it's a fern. it doesn't care. i care",
    "a leaf yellowed and i did a full investigation. verdict: it was just an old leaf",
    "someone asked if i 'do something with plants' and i said 'not professionally' which was a weird thing to say",
  ],
  dee_commutes: [
    "Train stopped between stations for 15 minutes. No announcement. We just sat in the dark together.",
    "Someone is eating a whole cantaloupe on the 7:40. With a spoon. Respect.",
    "Garage attendant knows my car now. Not me. My car.",
    "Merged onto the highway and immediately regretted every choice that led to this job.",
    "Nail clipper guy switched cars. I have never been so betrayed.",
    "Drove home a different way to avoid construction. Found different construction.",
    "The office moved my desk closer to the window and farther from the exit. Mixed feelings.",
    "Left at 5:01 and the garage line was already 20 cars deep. Everyone had the same idea.",
    "Podcast host said 'we're running long' at the 2 hour mark. So was my commute.",
    "The 'express' train made every stop. I asked. Nobody knew why.",
    "Got a seat. On a Monday. At 8am. Bought a lottery ticket at lunch.",
  ],
  cody_wrenches: [
    "guy asked if i could 'just take a quick look' at his transmission. aint no quick look at a transmission",
    "the wife found the receipt for the lift kit. we had a meeting",
    "coldest morning of the year and every battery in the county died at once",
    "dropped a wrench in the engine bay and it just vanished. its in the truck somewhere forever now",
    "customer wanted a 'diagnostic' for free. i want a lot of things for free",
    "deer season opened and i saw 4 deer on the drive to work and zero in the woods",
    "the shop dog ate a whole sleeve of crackers off my bench and looked proud of it",
    "put new tires on the wifes car and she said 'they look the same.' they are supposed to look the same",
    "gas station had 89 for the price of 87 by mistake. filled up twice",
    "buddy bought a truck 'for towing.' he owns nothing to tow",
    "hands are so dirty the sink cant fix it anymore. thats the job",
  ],
  priya_codes: [
    "The bug is back. The bug was never gone. The bug was waiting.",
    "Neighbor finished drilling. Started hammering. Growth.",
    "Standup was cancelled and I felt like a kid on a snow day.",
    "Wrote a comment that says 'do not touch this' above code I wrote. For me. From me.",
    "Tea count today: 4. Meeting count: 6. The ratio is off.",
    "The new hire asked why we do it this way and I said 'history' which is not an answer.",
    "Fixed one test. Broke four. Net progress: emotional.",
    "The second monitor is now just for the clock.",
    "My chair noise is louder. It's a new pitch. I'm naming it.",
    "Someone said 'quick sync' and it was 50 minutes. Quick.",
    "Turned my camera on for a meeting and realized I've been wearing the same hoodie for 3 days on camera. Nobody said anything. Nobody would.",
  ],
  mo_the_dad: [
    "The 4 year old asked if the vacuum is alive. I said no. He said 'then why does it scream.' Fair.",
    "The little one put a sock in the toaster. The toaster is fine. The sock is retired.",
    "Bedtime took an hour and then I fell asleep in the tiny chair. Woke up at 2am with a stuffed giraffe on my face.",
    "The 4 year old told a stranger that daddy 'doesn't know how to do hair.' Correct, but rude.",
    "Made dinner. Nobody ate dinner. Ate three dinners.",
    "Found a raisin in the car seat that could be from any month this year.",
    "The little one said her first full sentence today. It was 'no, mine.' She's ready for the world.",
    "The 4 year old wants to know why the moon is out in the daytime and I've run out of ways to say 'it just is.'",
    "Daycare sent a note home that says 'ask him about the frog.' I asked. It was a whole thing.",
    "Coffee reheated three times. Drank it cold. It's fine. Everything's fine.",
    "Kids asleep. Dishwasher running. Wife and I watched 11 minutes of a show and both fell asleep. Great night.",
  ],
  zoe_thrifts: [
    "$3 corduroy pants!! they're 4 inches too long and i'm keeping them anyway",
    "gloria sewed through my finger a little. we're taking a break",
    "the thrift store put out halloween stuff in september and i bought a cape. for what. we'll see",
    "found a sweater that smells like someone's grandma's house and i mean that as the highest compliment",
    "laundromat tv is stuck on a cooking channel and i've learned so much about brisket",
    "hemmed a skirt in 20 minutes. checked it. hemmed the wrong side. classic",
    "someone at the thrift store was buying 8 identical mugs and i want to know everything",
    "my closet has 30 things and i wear 4. the other 26 are 'for events'",
    "bought a $2 belt and it's the best belt i've ever owned. capitalism is fake",
    "the good jeans have a hole now. patching them. the patch will be a whole personality",
    "found a vintage tee with a fun run from 1996 on it. i have never run. i will wear it running errands",
  ],
  hank_fishes: [
    "Fog on the water. Couldnt see the end of the dock",
    "One catfish. Ugly one. Kept him",
    "Rufus barked at a turtle for ten minutes",
    "Bait shop was closed. Used bread. Worked fine",
    "Grill needs a new grate. Grilled on it anyway",
    "Wind came up. Went home",
    "Neighbor says the crappie are biting by the bridge. Well see",
    "Coffee was cold by the time I got to the dock. Drank it",
    "Truck started. Good day",
    "Nothing biting so I just sat there. Not the worst thing",
    "Lost a good lure to a stump. That stump has a collection",
  ],
  anna_bakes: [
    "Gary 2 is thriving! Loaf number 4 this week. My husband has started giving bread to the mailman.",
    "Made cookies for the neighbors and ate 6 'testing.' Quality control is serious work!!",
    "Oven thermometer says 350. Oven dial says 350. Cookies say 400.",
    "Tried a fancy recipe with 'laminated dough.' Three hours. Butter everywhere. They were... fine!",
    "Somebody at work asked for the recipe and I said 'it's just the one on the bag' and now she doesn't believe me!",
    "Bread rose too much and stuck to the oven. The oven and I are still not speaking.",
    "Brought scones to the neighbors and they gave me zucchini. This is how it works now. A trade economy!",
    "New flour. Same bread. Somehow better. I don't ask questions.",
    "The smoke alarm went off at 6am. I was just toasting a bagel. Even the alarm doesn't trust me anymore!!",
    "Cake for a coworker's birthday. Wrote 'Happy Birthday Gary.' Her name is not Gary. Gary is my starter. I've been baking too much.",
    "Made 3 pies for 4 people. Correct math.",
  ],
  lurker_liv: [
    "pasta again",
    "bus was late",
    "trimmed my bangs. fine",
    "watched half a movie",
    "cloudy",
    "did the laundry. didnt fold it",
    "coffee",
    "walked to the store and back",
    "it's dark early now",
    "napped",
    "bought socks",
    "slow day",
  ],
  steve_at_work: [
    "The printer has a new error message. It's in a font I've never seen.",
    "Fridge cleanout produced a Tupperware nobody claimed. It has been placed on the 'free' table. It is still there.",
    "Someone booked the big conference room for a 1 on 1.",
    "New hire asked where the good pens are. Told him. Regret it.",
    "The thermostat war has a new front: someone brought a space heater.",
    "The 9:15 popcorn guy was out sick. The whole floor felt off.",
    "Reply-all chain about the reply-all chain is now 34 messages.",
    "Parking lot repainted again. Somehow fewer spots.",
    "Coffee machine's 12 buttons now light up in a sequence. Nobody knows what it means.",
    "The elevator inspection certificate expired in 2022. I take the stairs.",
    "Leftover birthday cake for Pam. Still no Pam.",
  ],
  noodle_nina: [
    "why do we say 'heads up' when the thing is usually coming at your head",
    "wait a ceiling is just a floor that gave up",
    "carrots are orange because we decided. before that they were purple. we just decided",
    "if you think about it a spoon is a tiny bowl on a stick. no. yes",
    "how many times have you said 'the thing' and meant it. i think 40% of my sentences",
    "my hand fell asleep and i tried to wake it up by shaking it like it was a person",
    "wait does a fish get thirsty",
    "the alphabet is in an order and nobody knows why and we all just went with it",
    "a pancake is just a very thin cake that gave up on frosting",
    "bees make honey and we just took it. we took it and named it",
    "if you wear socks to bed are you 'in bed' or 'ready to leave' emotionally",
    "wait why is it called a building if its already built",
  ],
  carlos_mx: [
    "Pickup game got rained out so we played in the parking garage. Ball went off a car. We left fast.",
    "My cousin bought a whistle and now thinks he's the ref. No manches.",
    "Mi mamá watched 10 minutes of the match and asked why they don't just kick it in. Bueno, mamá.",
    "The keeper on our team is 44 and still the best player. Not close.",
    "Lost 5-1 and my cousin said 'we had good moments.' We had one moment.",
    "Watched a match in the kitchen because the TV was 'for the novela.' Fair. Won anyway!!",
    "Family dinner turned into a 2 hour argument about a penalty from 2014. Nobody left.",
    "Ay, the ref today. Just the ref. That's the post.",
    "New cleats. Same touch. La neta the cleats were never the problem.",
    "Woke up at 5 for a match, fell asleep at 5:40, woke up at the final whistle. 0-0. Perfect.",
    "My cousin scored and celebrated for longer than the game lasted.",
  ],
  gina_retail: [
    "so a lady returned a candle that was 'too smelly.' it is a candle",
    "closing shift and the last customer was walking around with a cart and no items for 20 min",
    "someone asked for the manager and i said 'she's off' and they said 'then who's in charge' and i said 'the schedule'",
    "kid knocked over a whole display of cans and the mom said 'well thats what you get paid for.' ok",
    "break room has a new sign that says 'be kind' and someone wrote 'to who' under it",
    "got a 6am truck shift and the truck came at 9",
    "customer said 'i know you dont make the rules' and then yelled at me about the rules",
    "found a wallet in the parking lot and the guy came back for it and gave me a $2 reward. 2 dollars",
    "someone left a shoe in the fitting room. one shoe. they left in one shoe",
    "black friday schedule came out and i just laughed",
    "regular brought me a coffee today and i almost cried at the register. it was a rough week",
  ],
  ben_walks: [
    "Mayor was on my porch when I got home. He acted like it was his porch. Maybe it is.",
    "Walked 14,000 steps and 3,000 of them were pacing during a phone call.",
    "The bakery started a loyalty card. I'm two stamps away and I've been going for a year.",
    "Passed a house that puts out a bowl of water for dogs and a bowl of candy for people. Good house.",
    "Podcast about the history of paper. Two episodes in. It's more than you'd think.",
    "Cold morning. Walked anyway. Ears are still cold at noon.",
    "Someone put a chair at the top of the hill on my route with a sign that says 'sit.' I sat.",
    "Tried a new route. Got mildly lost. Found a better bakery. Conflicted.",
    "Step counter says 'you've been inactive.' I've walked to the kitchen 11 times.",
    "Mayor has a rival now. Orange cat, two streets over. Tensions are high.",
    "Walked past the same construction site for 3 months. It's still a hole. A very well-fenced hole.",
  ],
  syd_music: [
    "GOT THE PRESALE. no fees. i mean there were fees. but i got it",
    "the venue changed the age limit the day of and the line got real quiet",
    "record store had a $1 bin and i spent an hour and found one good one. it was worth the hour",
    "opener played 4 songs. headliner played 2 hours. still thought about the opener the whole drive home",
    "tall guy was not there tonight. i felt weirdly abandoned",
    "MY NEEDLE BROKE. mid song. the good song",
    "the encore was one song and everyone knew it was coming and we still lost it",
    "someone spilled a whole beer on my shoes in the pit and said 'my bad' like it was a light bump",
    "made a playlist for a road trip and we got there before the second song",
    "the merch guy remembered me. either a good sign or i need to slow down",
    "ears still ringing from thursday. it's saturday. no regrets",
  ],
  aunt_deb: [
    "Biscuit found a dead bird and brought it inside like a gift... thanks buddy LOL",
    "Gary put the Christmas lights up in October 'to beat the rush.' There is no rush. It's October!",
    "My niece has a 'travel team' now and I've learned it means we travel!",
    "Casserole came out perfect and nobody was home to see it... photo attached (in my heart)",
    "Coupon for $2 off a thing I was going to buy anyway. That's the good stuff!",
    "Neighbor's leaf blower at 7am on a SATURDAY... some people!",
    "Anyone else's dog scared of the ceiling fan? Just Biscuit? Ok.",
    "Made 4 dozen deviled eggs for the game. Gone by halftime. I don't know what to tell you.",
    "The grocery store moved the bread and I wandered for 10 minutes like a lost child LOL",
    "Gary tried to fix the sink. We now have a plumber AND a story.",
    "Fall candle season!! The house smells like a pumpkin exploded and I love it ❤️",
    "My sister sent a 3 minute voice memo that could have been 'yes.'",
  ],
};
